## Overview

This notebook will examine the following questions:

1. How many characters are there? What are their names?
1. For each character, find out who has the most lines across all episodes
1. What is the average of words per line for each character?
1. What is the most common word per character
1. Number of episodes where the character does not have a line, for each character
1. Number of time "That's what she said" joke comes up
    *     Include five examples of the joke
1. The average percent of lines each character contributed each episode per season.


In order to accomplish this, I will use the data cleaned in the notebook available at `code/the_office_data.ipynb` and stored in `data/cleaned_office_data.csv`.

### Task #1.  How many characters are there, what are their names

This task was essentially done as a part of the data cleaning effort. There are a number of ways in which we *could* answer it. However, I think that the way which makes the most sense is to appeal to the known authority on all things "The Office" -- in this case that authority will be the wiki.


I will further limit the characters to those which have lines in our script. Otherwise, it might be confusing for those who examine this data after me. After cleaning the data, this may be accomplished with relative ease:

In [8]:
import pandas as pd
df = pd.read_csv('../data/cleaned_office_data.csv')
characters = df.sort_values('speaker').speaker.unique()

To find the number of characters, we examine the length and find 115:

In [10]:
len(characters)

115

and to print their names it's simply a print statement:

In [11]:
for character in characters:
    print(character)

aj
alex
andy
angela
astrid
ben
billy
brandon
brenda
brian
bruce
cameron
carol
cathy
charles
clark
craig
creed
dan
danny
darryl
david
deangelo
devon
donna
dwight
ed
elizabeth
ellen
erin
esther
fannie
frank
fred
gabe
gabor
gideon
gil
glenn
hank
hannah
helene
henry
holly
hunter
ira
irene
isabel
jada
jake
jan
jeb
jerry
jessica
jim
jo
jordan
josh
justin
justine
karen
kathy
katy
kelly
kendall
kenny
kevin
leo
lonny
lynn
madge
martin
matt
meemaw
megan
melissa
melvina
meredith
merv
michael
mose
nate
nellie
nick
oscar
pam
penny
pete
philip
phillip
phyllis
rachel
ravi
robert
rolando
rolf
rory
roy
ryan
sasha
shirley
stanley
stephanie
teddy
toby
todd
tom
tony
trevor
troy
val
vikram
walter
wolf
zeke

I have omitted last names here because the script does not contain them. However, if desired, they may be obtained by cross referencing the wiki.

### Task #2. For each character, find out who has the most lines across all episodes

This task description is slightly ambiguous. I could interpret it as either:

1. Which character has the most lines across all episodes
1. Which character has the most lines in each episode

Since it is not possible to ask for clarification in this assignment, I will perform both queries.

#### 2a. Which character has the most lines across all episodes

The answer to this (unsurprisingly) is Michael. To find this, I grouped the data by speaker, and then counted the elements each speaker had and sorted in a descending fashion:

In [74]:
df.groupby('speaker').size().reset_index(name='line_counts').sort_values( 'line_counts', ascending=False).iloc[0].speaker

'michael'

#### 2b. Which character has the most lines in each episode

This question is a bit more involved than the last one. The high level approach here is to group by season, episode, AND speaker. However, it is tricky because pandas does not provide a native "unique by multiple columns" method.

So, in lieu of that, I sorted them by their (descending) line_counts and used the fact that the `.drop_duplicates()` method retains only the first matching element.

In [15]:
per_episode = df.groupby(['season', 'episode','speaker']).size().reset_index(name='line_counts').sort_values('line_counts', ascending=False).reset_index(drop=True)
per_episode.head()

   season  episode  speaker  line_counts
0       4       14  michael          167
1       4        4  michael          162
2       4        1  michael          160
3       4        2  michael          158
4       4        3  michael          156

Then, I dropped duplicates of season and episode and finally pulled the rows out of the original dataframe and sorted the results by season / episode to make them more readable.

Hopefully reading this chart is fairly intuitive. The character with the most lines for a given episode may be found in the `speaker` column. For example, in season 1 episode 1, Michael had the most lines:

In [19]:
pd.set_option('display.max_rows', 186)
per_episode = per_episode.iloc[per_episode[['season', 'episode']].drop_duplicates().index].sort_values(['season', 'episode']).reset_index(drop=True)
per_episode

     season  episode   speaker  line_counts
0         1        1   michael           98
1         1        2   michael          103
2         1        3    dwight           88
3         1        4   michael          111
4         1        5   michael          135
5         1        6   michael          128
6         2        1   michael          138
7         2        2   michael          112
8         2        3   michael          120
9         2        4    dwight           83
10        2        5   michael          150
11        2        6   michael          102
12        2        7   michael           88
13        2        8   michael          147
14        2        9   michael          131
15        2       10   michael           95
16        2       11   michael          116
17        2       12   michael          146
18        2       13   michael          114
19        2       14   michael          127
20        2       15   michael           88
21        2       16   michael           53
22        2       17   michael           75
23        2       18   michael           83
24        2       19   michael           99
25        2       20    dwight           92
26        2       21   michael           95
27        2       22   michael          112
28        3        1   michael           63
29        3        2   michael          123
30        3        3   michael           83
31        3        4   michael          106
32        3        5    dwight           57
33        3        6   michael           77
34        3        7   michael           70
35        3        8   michael          153
36        3        9   michael           54
37        3       10   michael          116
38        3       11   michael          100
39        3       12   michael           48
40        3       13   michael           49
41        3       14   michael           77
42        3       15   michael           49
43        3       16   michael           65
44        3       17   michael           85
45        3       18   michael          107
46        3       19   michael          103
47        3       20       jim           74
48        3       21   michael           92
49        3       22   michael          145
50        3       23   michael          123
51        4        1   michael          160
52        4        2   michael          158
53        4        3   michael          156
54        4        4   michael          162
55        4        5   michael           93
56        4        6   michael           93
57        4        7   michael           82
58        4        8   michael           89
59        4        9   michael          102
60        4       10   michael          101
61        4       11   michael          104
62        4       12   michael           99
63        4       13   michael           77
64        4       14   michael          167
65        5        1   michael          132
66        5        2   michael           68
67        5        3   michael           83
68        5        4   michael           96
69        5        5   michael          107
70        5        6       jim          112
71        5        7   michael           77
72        5        8   michael           90
73        5        9   michael          100
74        5       10   michael           65
75        5       11    dwight           66
76        5       12   michael           91
77        5       13   michael          119
78        5       14   michael           55
79        5       15   michael           50
80        5       16   michael           88
81        5       17   michael          113
82        5       18   michael          104
83        5       19   michael           88
84        5       20   michael           80
85        5       21   michael           46
86        5       22   michael           96
87        5       23   michael           76
88        5       24   michael           95
89        5       25   michael           85
90        5       26   michael           55
91        6        1   michael           98
92        6        2   michael           72
93        6        3       jim           91
94        6        4   michael          132
95        6        5   michael          122
96        6        6   michael           85
97        6        7   michael           85
98        6        8   michael          115
99        6        9   michael           67
100       6       10   michael           71
101       6       11   michael           69
102       6       12   michael           95
103       6       13   michael           44
104       6       14   michael           82
105       6       15   michael           69
106       6       16       jim          135
107       6       17        jo           53
108       6       18   michael           86
109       6       19   michael           74
110       6       20      erin           52
111       6       21   michael           88
112       6       22   michael           92
113       6       23   michael           82
114       6       24   michael           67
115       7        1   michael           58
116       7        2    dwight           48
117       7        3      andy           49
118       7        4   michael           89
119       7        5   michael           85
120       7        6   michael           59
121       7        7   michael           75
122       7        8   michael           56
123       7        9   michael           68
124       7       10   michael           56
125       7       11   michael          130
126       7       12   michael           75
127       7       13      andy           51
128       7       14   michael           43
129       7       15   michael           73
130       7       16   michael           33
131       7       17   michael           57
132       7       18   michael           73
133       7       19  deangelo           84
134       7       20   michael           83
135       7       21   michael          116
136       7       22  deangelo           90
137       7       23    dwight           74
138       7       24       jim           90
139       8        1      andy           52
140       8        2      andy           86
141       8        3      andy           63
142       8        4      andy           69
143       8        5      erin           36
144       8        6      andy           56
145       8        7       pam           66
146       8        8      andy           58
147       8        9      andy           60
148       8       10      andy           88
149       8       11      andy           44
150       8       12      erin           58
151       8       13       jim           73
152       8       14    dwight           67
153       8       15    dwight           63
154       8       16    dwight           60
155       8       17    dwight           53
156       8       18       jim           45
157       8       19    nellie           42
158       8       20      andy           48
159       8       21      andy           54
160       8       22      andy           41
161       8       23    dwight           56
162       8       24      andy           49
163       9        1    dwight           42
164       9        2       jim           39
165       9        3      andy           44
166       9        4       jim           60
167       9        5      andy           50
168       9        6      andy           54
169       9        7    dwight           53
170       9        8    dwight           57
171       9        9    dwight           59
172       9       10       pam           44
173       9       11    dwight           41
174       9       12       pam           48
175       9       13    dwight           88
176       9       14       pam           57
177       9       15      andy           62
178       9       16      andy           83
179       9       17    dwight           51
180       9       18       pam           42
181       9       19    dwight           61
182       9       20      andy           39
183       9       21      andy           68
184       9       22       jim           91
185       9       23    dwight           76

### Task #3. What is the average of words per line for each character?

In this task, I will determine how many words an average line contains for each given character. I do this by splitting the lines into words using a fairly naive regex pattern that matches only (case insensitive) letters a-z

In [21]:
import re
df['word_count'] = df.line_text.apply(lambda x: len(re.findall("[a-zA-Z_]+", x)))

Then, I group the rows by speaker and take an average which I round to 2 decimals for readability

In [27]:
average_word_count_df = df[["speaker", "word_count"]].groupby('speaker').mean().sort_values('speaker')
average_word_count_df.word_count = average_word_count_df.word_count.apply(lambda x: round(x, 2))
average_word_count_df.reset_index()

       speaker  word_count
0           aj        5.65
1         alex       24.20
2         andy       13.44
3       angela        9.85
4       astrid        2.67
5          ben        7.75
6        billy        8.75
7      brandon        8.72
8       brenda        5.71
9        brian       10.70
10       bruce        2.00
11     cameron        8.33
12       carol        6.48
13       cathy        8.60
14     charles        8.89
15       clark       10.70
16       craig       11.67
17       creed       11.58
18         dan        7.00
19       danny        9.21
20      darryl       10.45
21       david       11.40
22    deangelo       15.95
23       devon       12.44
24       donna        8.02
25      dwight       12.72
26          ed        7.91
27   elizabeth        5.40
28       ellen        4.33
29        erin       10.42
30      esther       12.62
31      fannie       14.47
32       frank       11.00
33        fred       14.78
34        gabe       15.44
35       gabor       15.00
36      gideon       13.50
37         gil        6.67
38       glenn        8.00
39        hank        8.80
40      hannah        6.39
41      helene       12.29
42       henry       14.33
43       holly        9.53
44      hunter        3.50
45         ira        6.78
46       irene       11.26
47      isabel        7.45
48        jada        5.14
49        jake        5.21
50         jan       10.90
51         jeb       16.33
52       jerry       12.07
53     jessica        6.73
54         jim       10.42
55          jo       16.87
56      jordan        5.46
57        josh        9.11
58      justin        4.93
59     justine        8.00
60       karen        9.29
61       kathy        7.30
62        katy        6.00
63       kelly       12.02
64     kendall       18.75
65       kenny        7.53
66       kevin        9.43
67         leo        5.33
68       lonny        8.50
69        lynn        3.75
70       madge        4.43
71      martin       13.39
72        matt        5.40
73      meemaw        9.00
74       megan        7.70
75     melissa        6.74
76     melvina       16.60
77    meredith        9.18
78        merv       21.80
79     michael       15.44
80        mose        4.81
81        nate       14.05
82      nellie       14.19
83        nick       18.29
84       oscar        9.94
85         pam       10.01
86       penny        8.45
87        pete        9.04
88      philip        1.00
89     phillip        1.00
90     phyllis        8.95
91      rachel        6.00
92        ravi       14.00
93      robert       15.29
94     rolando       11.50
95        rolf       10.75
96        rory       11.00
97         roy        9.54
98        ryan       10.98
99       sasha        5.60
100    shirley        7.65
101    stanley        9.63
102  stephanie        3.89
103      teddy        2.50
104       toby       11.06
105       todd       16.05
106        tom        8.03
107       tony        6.58
108     trevor       10.87
109       troy        8.50
110        val        6.52
111     vikram        7.90
112     walter       11.80
113       wolf       10.10
114       zeke        8.60

### Task #4. What is the most common word per character?

Here I will begin by using the same naive regex definition of a word as I used previously to ensure that all words are delimited by spaces.

In [28]:
from stopwords import stopwords
stopword_set = set(stopwords)
most_common_word_df = pd.DataFrame(df)
most_common_word_df['line_text'] = df.line_text.apply(lambda x: ' '.join(re.findall("[a-zA-Z_]+", x)))

Next, I will combine all the lines each character says into a single long string (per character) and drop the duplicates since we only need one row per character now.

In [31]:
joined_line_series = most_common_word_df.groupby('speaker').line_text.transform(lambda x: ' '.join(x))
most_common_word_df['joined_lines'] = joined_line_series
most_common_word_df = most_common_word_df.drop_duplicates('speaker')

Then I will remove stopwords (otherwise the results of this query will be especially boring). And finally, I will use the Counter python class to extract the most common word.

In [36]:
from collections import Counter
most_common_word_df['most_common_word'] = most_common_word_df.joined_lines.apply(lambda x: Counter([word for word in x.split() if word.lower() not in stopword_set]).most_common(1))
most_common_word_df.most_common_word = most_common_word_df[most_common_word_df.most_common_word.apply(lambda x: x != [])].most_common_word.apply(lambda x: x[0][0])
most_common_word_df[["speaker", "most_common_word"]].sort_values('speaker').reset_index(drop=True).dropna()

       speaker most_common_word
1         alex               Uh
2         andy              Hey
3       angela            gonna
4       astrid            Mommy
5          ben          Michael
6        billy             fine
7      brandon              Val
8       brenda             Yeah
9        brian              Hey
11     cameron           Dwight
12       carol          Michael
14     charles             Yeah
15       clark               uh
16       craig              Hey
17       creed              Huh
19       danny              Hey
20      darryl             real
21       david            David
22    deangelo            drink
23       devon            Creed
24       donna               uh
25      dwight               Pa
26          ed             Yeah
27   elizabeth              Hey
28       ellen          thought
29        erin         changing
30      esther           Dwight
31      fannie       approaches
32       frank            gonna
33        fred             Yeah
34        gabe       applauding
35       gabor              mom
36      gideon            North
38       glenn          postage
39        hank           Dwight
40      hannah              Hey
41      helene            walks
42       henry           Dwight
43       holly               uh
44      hunter              Hey
45         ira               Uh
46       irene        introduce
47      isabel              Jim
48        jada            Santa
49        jake         computer
50         jan             cell
51         jeb              dug
52       jerry              Pam
53     jessica             call
54         jim             told
55          jo             love
57        josh          Michael
58      justin             Cool
59     justine            phone
60       karen              Jim
62        katy             hand
63       kelly         customer
64     kendall     speakerphone
65       kenny          Bermuda
66       kevin             Yeah
67         leo             weed
69        lynn             Lynn
70       madge              Hey
71      martin          passing
73      meemaw             lost
74       megan         password
75     melissa           eighth
76     melvina       babysitter
77    meredith          Michael
79     michael              Jim
80        mose         promised
81        nate             Hola
82      nellie              job
84       oscar             guys
86       penny            Kevin
87        pete          perfect
88      philip             Mama
89     phillip            cries
90     phyllis       downsizing
91      rachel        Wonderful
92        ravi              Jim
93      robert             nice
94     rolando            phone
95        rolf     interviewing
96        rory            bring
97         roy              Hey
98        ryan              Hey
100    shirley              big
102  stephanie            David
103      teddy             Suck
104       toby              Hey
105       todd              Hey
106        tom              Hey
107       tony            Karen
108     trevor             safe
109       troy              Hey
110        val              Hey
111     vikram            mixed
112     walter             work
113       wolf              Man
114       zeke           Dwight

* Examining this shows that we might want to consider expanding our collection of stopwords. For example, it would be reasonable to include words like "Hey" and "Uh" in the stopword list
* There is also a bit of an open question as to whether we might want to exclude character names
* However, this result is decently interesting, so for the scope of this project I will leave it as-is

### Task #5. Number of episodes where the character does not have a line, for each character

In order to accomplish this, I took a reverse-approach. Specifically, I started by getting the total count of episodes in our project

In [37]:
total_episode_count = len(df.groupby(['season', 'episode']).size())
total_episode_count

186

Next, I grouped the rows of the data by speaker, season, and episode to get the count of episodes in which each character *does* have a line

In [40]:
speechless_episode_df = df.groupby(['speaker', 'season', 'episode']).count().groupby('speaker').size().reset_index(name="episode_count").sort_values('episode_count', ascending=False)
speechless_episode_df.head()

   speaker  episode_count
25  dwight            186
54     jim            185
85     pam            182
66   kevin            180
3   angela            175

Finally, I subtracted the number of episodes in which a character speaks from the total episode count to wind up with the speechless episode count

In [41]:
speechless_episode_df['speechless_episode_count'] = speechless_episode_df.episode_count.apply(lambda x: total_episode_count - x)
speechless_episode_df[['speaker', 'speechless_episode_count']].reset_index(drop=True)

       speaker  speechless_episode_count
0       dwight                         0
1          jim                         1
2          pam                         4
3        kevin                         6
4       angela                        11
5      stanley                        15
6      phyllis                        16
7        oscar                        20
8        kelly                        41
9         andy                        42
10    meredith                        43
11        ryan                        45
12       creed                        48
13     michael                        49
14        toby                        67
15      darryl                        81
16        erin                        88
17        gabe                       139
18         jan                       142
19      nellie                       153
20         roy                       156
21       david                       158
22       karen                       160
23        pete                       164
24      robert                       165
25       clark                       166
26       holly                       169
27        hank                       172
28        todd                       173
29         val                       175
30        nate                       176
31          jo                       177
32        mose                       178
33        josh                       179
34     charles                       179
35       cathy                       179
36       carol                       179
37       kathy                       181
38       kenny                       181
39       brian                       181
40      helene                       181
41      esther                       181
42        nick                       182
43      hannah                       182
44    deangelo                       182
45     jessica                       182
46      hunter                       183
47       donna                       183
48       madge                       183
49          aj                       183
50       glenn                       183
51        zeke                       183
52       sasha                       183
53   stephanie                       183
54         tom                       183
55        ravi                       183
56        troy                       183
57      jordan                       183
58        katy                       183
59        matt                       183
60       lonny                       183
61        lynn                       183
62     melissa                       184
63     kendall                       184
64      martin                       184
65        tony                       184
66      vikram                       184
67      trevor                       184
68          ed                       184
69       danny                       184
70       devon                       184
71       irene                       184
72        jake                       184
73     brandon                       184
74   elizabeth                       184
75         gil                       184
76        jada                       184
77      isabel                       184
78     justine                       184
79      rachel                       184
80     phillip                       184
81     rolando                       184
82       megan                       184
83         ira                       185
84      gideon                       185
85       gabor                       185
86       henry                       185
87       ellen                       185
88      fannie                       185
89       frank                       185
90        fred                       185
91       bruce                       185
92      brenda                       185
93         ben                       185
94       billy                       185
95      astrid                       185
96     cameron                       185
97       craig                       185
98         dan                       185
99        alex                       185
100    melvina                       185
101        leo                       185
102       merv                       185
103      jerry                       185
104     justin                       185
105        jeb                       185
106     meemaw                       185
107       rolf                       185
108       rory                       185
109      penny                       185
110     philip                       185
111      teddy                       185
112    shirley                       185
113     walter                       185
114       wolf                       185

### Task #6. Number of times "That's what she said" joke comes up

This task was a bit more interesting. Not every reference to "that's what she said" is unique, nor does every reference to "that's what she said" contain the full quote.

Upon examining the data that occurss by filtering out "what she s" - the results seem largely satisfactory:

In [44]:
twss_df = df[df.line_text.apply(lambda x: "what she s" in x.lower())].reset_index(drop=True)

,id,season,episode,scene,line_text,speaker,deleted,word_count
0,2545,2,2,24,That's what she said. Pam?,michael,False,6
1,2547,2,2,24,"That's what she sai [clears throat] Nope, but...",michael,False,13
2,2591,2,2,34,Does that include 'That's What She Said'?,jim,False,8
3,2594,2,2,34,THAT'S WHAT SHE SAID!,michael,False,5
4,5325,2,10,2,"A, that's what she said, and B, I wanted it to...",michael,False,27
5,6322,2,12,33,That's what she said.,dwight,False,5
6,6353,2,12,38,"Uh, that's what she said. See, haven't lost m...",michael,True,23
7,7644,2,17,6,That's what she said!,michael,False,5
8,8872,2,21,22,That's what she said. [Jim mouths these words ...,michael,False,64
9,9624,3,1,49,I am glad that today spurred social change. T...,michael,False,42
10,10904,3,5,59,That's what she said. [Stanley and Michael bot...,stanley,False,10
11,12594,3,10,49,Oh. [She whispers in his ear. Michael starts t...,michael,False,15
12,13337,3,12,41,That's what she said.,dwight,False,5
13,14302,3,17,9,That's what she said.,michael,False,5
14,14374,3,17,23,Why is this so hard? That's what she said. Oh ...,jan,False,17
15,15386,3,20,11,"No, no. I need two men on this. That's what ...",michael,False,36
16,17570,4,2,6,Hey. Can you make that straighter? That's what...,michael,False,11
17,18960,4,4,45,And the best way to start is to hit start. And...,michael,False,65
18,20122,4,7,56,That's what I said. That's what she said.,michael,False,10
19,20125,4,7,56,That's what she said.,jim,False,5
20,20270,4,8,23,That's what she said.,michael,False,5
21,20272,4,8,23,That's what she said.,michael,False,5
22,20278,4,8,23,Come again? That's what she said? I don't know...,michael,False,16
23,20716,4,9,19,[yells] THAT'S WHAT SHE SAID! [Jan gets an evi...,michael,False,57
24,21481,4,12,2,[muffled] That's what she said.,michael,False,6
25,23150,5,1,111,[from his office] That's what she said.,michael,False,8
26,23911,5,4,30,"It squeaks when you bang it, that's what she s...",michael,False,23
27,24197,5,5,25,That's what she said.,michael,False,5
28,24755,5,6,27,[in New York] That's what she said! That's wha...,pam,False,18
29,28090,5,17,27,That's what she said! [David laughs],dwight,False,7
30,36371,6,18,9,That's what she said.,michael,False,5
31,40587,7,8,29,[grimacing] That's what she said. [leaves],michael,False,7
32,42260,7,13,1,"No, no. No, comedy is a place where the mind g...",david,False,23
33,43115,7,15,30,I'm not saying it won't be hard. But we can ma...,holly,False,20
34,44696,7,21,51,"[putting his shoes back on, talking to the cam...",michael,False,103
35,54088,9,5,29,Yeah. That's what she said.,creed,False,6
36,59751,9,23,68,That���s what she said.,michael,False,5

However, there are several duplicates here- so we should unique by episode scene

In [67]:
twss_df.season.astype(str) + twss_df.episode.astype(str) + twss_df.scene.astype(str)
twss_df['key'] = twss_df.apply(lambda x: '-'.join([str(x.season), str(x.episode), str(x.scene)]), axis=1)
twss_df = twss_df.drop_duplicates('key').reset_index(drop=True)
twss_df

,id,season,episode,scene,line_text,speaker,deleted,word_count,key
0,2545,2,2,24,That's what she said. Pam?,michael,False,6,2-2-24
1,2591,2,2,34,Does that include 'That's What She Said'?,jim,False,8,2-2-34
2,5325,2,10,2,"A, that's what she said, and B, I wanted it to...",michael,False,27,2-10-2
3,6322,2,12,33,That's what she said.,dwight,False,5,2-12-33
4,6353,2,12,38,"Uh, that's what she said. See, haven't lost m...",michael,True,23,2-12-38
5,7644,2,17,6,That's what she said!,michael,False,5,2-17-6
6,8872,2,21,22,That's what she said. [Jim mouths these words ...,michael,False,64,2-21-22
7,9624,3,1,49,I am glad that today spurred social change. T...,michael,False,42,3-1-49
8,10904,3,5,59,That's what she said. [Stanley and Michael bot...,stanley,False,10,3-5-59
9,12594,3,10,49,Oh. [She whispers in his ear. Michael starts t...,michael,False,15,3-10-49
10,13337,3,12,41,That's what she said.,dwight,False,5,3-12-41
11,14302,3,17,9,That's what she said.,michael,False,5,3-17-9
12,14374,3,17,23,Why is this so hard? That's what she said. Oh ...,jan,False,17,3-17-23
13,15386,3,20,11,"No, no. I need two men on this. That's what ...",michael,False,36,3-20-11
14,17570,4,2,6,Hey. Can you make that straighter? That's what...,michael,False,11,4-2-6
15,18960,4,4,45,And the best way to start is to hit start. And...,michael,False,65,4-4-45
16,20122,4,7,56,That's what I said. That's what she said.,michael,False,10,4-7-56
17,20270,4,8,23,That's what she said.,michael,False,5,4-8-23
18,20716,4,9,19,[yells] THAT'S WHAT SHE SAID! [Jan gets an evi...,michael,False,57,4-9-19
19,21481,4,12,2,[muffled] That's what she said.,michael,False,6,4-12-2
20,23150,5,1,111,[from his office] That's what she said.,michael,False,8,5-1-111
21,23911,5,4,30,"It squeaks when you bang it, that's what she s...",michael,False,23,5-4-30
22,24197,5,5,25,That's what she said.,michael,False,5,5-5-25
23,24755,5,6,27,[in New York] That's what she said! That's wha...,pam,False,18,5-6-27
24,28090,5,17,27,That's what she said! [David laughs],dwight,False,7,5-17-27
25,36371,6,18,9,That's what she said.,michael,False,5,6-18-9
26,40587,7,8,29,[grimacing] That's what she said. [leaves],michael,False,7,7-8-29
27,42260,7,13,1,"No, no. No, comedy is a place where the mind g...",david,False,23,7-13-1
28,43115,7,15,30,I'm not saying it won't be hard. But we can ma...,holly,False,20,7-15-30
29,44696,7,21,51,"[putting his shoes back on, talking to the cam...",michael,False,103,7-21-51
30,54088,9,5,29,Yeah. That's what she said.,creed,False,6,9-5-29
31,59751,9,23,68,That���s what she said.,michael,False,5,9-23-68

This looks reasonable, so a decent estimate of the number of "That's what she said" jokes would be 32:

In [68]:
len(twss_df)

32

### Task #6b. Five examples of the joke

The easiest way to do this is to manually pull the text from the scenes. After getting the season, episode, and scene from the readout of the preceding DataFrame, it's pretty straightforward to go into the script file and copy the relevant lines. 

I preferred a manual method here because there is not a simple way to script how much context should be included.

#### Example 1. from season 2, episode 2, scene 34

Michel: Attention, everyone! Hello! Ah, yes! I just want you to know that, uh, this is not my decision, but from here on out... we can no longer be friends. And when we talk about things here we must only discuss work-associated things.  And, uh, you can consider this my retirement from comedy. And in the future, if I want to say something funny or witty or do an impression, I will no longer, ever, do any of those things.


Jim: Does that include 'That's What She Said'?

Jim: Wow! That is really hard. You really think you can go all day long? Well, you always left me satisfied and smiling

Michael: THAT'S WHAT SHE SAID!

#### Example 2. from season 2, episode 12, scene 38

Oscar: [Jim popping Michael's bubble wrap cast] You should put butter on it.

Michael: Uh, that's what she said.  See, haven't lost my sense of humor.  No, no need, it was a non-stick grill.

#### Example 3. from season 2, episode 2, scene 24

Pam: Uh... my mother's coming.

Michael: That's what she sai [clears throat]  Nope, but... Okay. Well, suit yourself.

#### Example 4. from season 2, episode 10, scene 2

Kevin: [holds up the piece of tree he just cut off with a paper cutter] Well, sort of. Why did you get it so big?

Michael: A, that's what she said, and B, I wanted it to be impressive. The biggest day of the year deserves the biggest tree of the year.

#### Example 5. from season 2, episode 12, scene 33

Doctor: Does the skin look red and swollen?

Dwight: That's what she said.

### Task #7. The average percent of lines each character contributed each episode per season

I will interpret this as the "percent of lines per character per season" rather than the "percent of lines per character per episode per season" as the latter would be a bit redundant.

In order to do this, I begin by grouping rows by speaker and season and counting them

In [70]:
percent_per_season_df = df.groupby(['speaker', 'season']).size().reset_index(name="speaker_season_line_count")
percent_per_season_df.head()

  speaker  season  speaker_season_line_count
0      aj       5                         16
1      aj       7                         15
2    alex       5                         10
3    andy       3                        398
4    andy       4                        229

Next, I will find the total number of lines per season by grouping season and summing

In [71]:
total_lines_per_season = percent_per_season_df.groupby('season').sum().reset_index()[['season', 'speaker_season_line_count']]
total_lines_per_season.head()

   season  speaker_season_line_count
0       1                       1912
1       2                       7118
2       3                       7217
3       4                       5338
4       5                       7852

And finally, I will divide the speaker's line count by the total line count, multiply by 100, and round the answer to 2 decimal places to get the answer:

In [73]:
pd.set_option('display.max_rows', 329)
percent_per_season_df['percent_per_season'] =  percent_per_season_df.apply(lambda x: round(100 * x['speaker_season_line_count'] / total_lines_per_season[total_lines_per_season['season'] == x['season']].speaker_season_line_count.iloc[0], 2), axis=1)
percent_per_season_df[['speaker', 'season', 'percent_per_season']]

       speaker  season  percent_per_season
0           aj       5                0.20
1           aj       7                0.21
2         alex       5                0.13
3         andy       3                5.51
4         andy       4                4.29
5         andy       5                6.36
6         andy       6                7.62
7         andy       7                7.98
8         andy       8               17.00
9         andy       9                9.76
10      angela       1                1.67
11      angela       2                2.29
12      angela       3                3.37
13      angela       4                3.63
14      angela       5                2.83
15      angela       6                1.90
16      angela       7                2.31
17      angela       8                2.50
18      angela       9                5.88
19      astrid       7                0.04
20         ben       4                0.07
21       billy       2                0.06
22     brandon       8                0.27
23      brenda       2                0.10
24       brian       9                0.81
25       bruce       8                0.01
26     cameron       9                0.14
27       carol       2                0.73
28       carol       3                0.51
29       carol       7                0.21
30       carol       9                0.02
31       cathy       8                0.75
32     charles       5                2.83
33       clark       6                0.18
34       clark       9                3.78
35       craig       2                0.17
36       creed       2                1.08
37       creed       3                0.98
38       creed       4                1.37
39       creed       5                0.67
40       creed       6                0.54
41       creed       7                0.94
42       creed       8                0.51
43       creed       9                0.80
44         dan       2                0.01
45       danny       7                0.97
46      darryl       1                0.89
47      darryl       2                1.08
48      darryl       3                1.22
49      darryl       4                1.14
50      darryl       5                1.32
51      darryl       6                1.17
52      darryl       7                3.26
53      darryl       8                4.76
54      darryl       9                4.26
55       david       2                0.17
56       david       3                0.89
57       david       4                0.06
58       david       5                1.62
59       david       6                1.57
60       david       7                0.17
61       david       8                0.39
62       david       9                0.38
63    deangelo       7                3.62
64       devon       2                0.13
65       donna       6                1.04
66       donna       7                0.10
67      dwight       1               17.10
68      dwight       2               15.76
69      dwight       3               13.12
70      dwight       4               10.40
71      dwight       5               13.75
72      dwight       6               11.48
73      dwight       7               10.07
74      dwight       8               14.17
75      dwight       9               16.42
76          ed       2                0.13
77          ed       9                0.03
78   elizabeth       3                0.24
79   elizabeth       4                0.06
80       ellen       8                0.04
81        erin       5                0.69
82        erin       6                4.19
83        erin       7                4.49
84        erin       8                6.44
85        erin       9                5.82
86      esther       9                0.32
87      fannie       9                0.29
88       frank       9                0.12
89        fred       7                0.13
90        gabe       6                1.19
91        gabe       7                3.01
92        gabe       8                1.80
93        gabe       9                0.31
94       gabor       9                0.05
95      gideon       8                0.03
96         gil       2                0.03
97         gil       3                0.06
98       glenn       8                0.06
99       glenn       9                0.03
100       hank       2                0.07
101       hank       4                0.13
102       hank       5                0.23
103       hank       6                0.01
104       hank       7                0.10
105       hank       8                0.06
106       hank       9                0.06
107     hannah       3                0.32
108     helene       6                0.58
109     helene       7                0.07
110     helene       9                0.03
111      henry       9                0.05
112      holly       4                1.37
113      holly       5                3.54
114      holly       7                3.77
115     hunter       3                0.11
116        ira       2                0.13
117      irene       8                0.34
118     isabel       6                0.40
119       jada       7                0.31
120       jake       2                0.38
121       jake       8                0.01
122        jan       1                1.99
123        jan       2                4.00
124        jan       3                4.13
125        jan       4                4.03
126        jan       5                0.82
127        jan       7                0.24
128        jan       9                0.51
129        jeb       9                0.18
130      jerry       6                0.19
131    jessica       5                0.04
132    jessica       8                0.79
133        jim       1               14.91
134        jim       2               12.81
135        jim       3               10.92
136        jim       4               12.83
137        jim       5               11.21
138        jim       6               12.93
139        jim       7                9.81
140        jim       8               13.02
141        jim       9               12.26
142         jo       6                1.90
143         jo       7                0.81
144     jordan       7                0.19
145       josh       2                0.15
146       josh       3                0.75
147     justin       4                0.26
148    justine       7                0.03
149    justine       8                0.04
150      karen       3                4.06
151      karen       4                0.47
152      karen       5                0.28
153      karen       7                0.01
154      kathy       6                0.04
155      kathy       8                0.10
156       katy       1                3.82
157       katy       2                0.37
158      kelly       1                0.21
159      kelly       2                1.62
160      kelly       3                2.44
161      kelly       4                1.89
162      kelly       5                2.00
163      kelly       6                1.68
164      kelly       7                2.22
165      kelly       8                1.89
166      kelly       9                0.21
167    kendall       5                0.10
168      kenny       3                0.15
169      kenny       8                0.07
170      kenny       9                0.02
171      kevin       1                1.57
172      kevin       2                2.23
173      kevin       3                2.94
174      kevin       4                2.75
175      kevin       5                2.39
176      kevin       6                3.16
177      kevin       7                3.42
178      kevin       8                3.74
179      kevin       9                4.09
180        leo       5                0.04
181      lonny       1                0.26
182      lonny       2                0.04
183      lonny       3                0.17
184       lynn       5                0.20
185      madge       1                0.16
186      madge       2                0.03
187      madge       3                0.03
188     martin       3                0.25
189       matt       6                0.14
190     meemaw       7                0.01
191      megan       6                0.04
192      megan       8                0.10
193    melissa       2                0.24
194    melissa       3                0.08
195    melvina       9                0.08
196   meredith       1                0.94
197   meredith       2                0.59
198   meredith       3                0.83
199   meredith       4                1.16
200   meredith       5                1.46
201   meredith       6                1.15
202   meredith       7                1.00
203   meredith       8                1.27
204   meredith       9                1.75
205       merv       7                0.14
206    michael       1               33.68
207    michael       2               32.80
208    michael       3               27.71
209    michael       4               30.78
210    michael       5               27.81
211    michael       6               27.71
212    michael       7               20.10
213    michael       9                0.03
214       mose       4                0.24
215       mose       7                0.04
216       mose       8                0.10
217       mose       9                0.14
218       nate       7                0.37
219       nate       8                0.36
220       nate       9                0.09
221     nellie       7                0.13
222     nellie       8                3.49
223     nellie       9                4.41
224       nick       4                0.24
225       nick       6                0.25
226      oscar       1                3.03
227      oscar       2                1.84
228      oscar       3                1.00
229      oscar       4                2.10
230      oscar       5                2.75
231      oscar       6                2.47
232      oscar       7                2.81
233      oscar       8                3.55
234      oscar       9                4.55
235        pam       1               11.45
236        pam       2               10.30
237        pam       3                9.21
238        pam       4                9.91
239        pam       5                9.09
240        pam       6                9.84
241        pam       7                8.76
242        pam       8                7.15
243        pam       9               11.29
244      penny       6                0.15
245       pete       5                0.19
246       pete       6                0.10
247       pete       9                2.94
248     philip       9                0.02
249    phillip       9                0.06
250    phyllis       1                0.58
251    phyllis       2                1.91
252    phyllis       3                1.55
253    phyllis       4                1.85
254    phyllis       5                2.33
255    phyllis       6                1.92
256    phyllis       7                2.12
257    phyllis       8                1.84
258    phyllis       9                1.96
259     rachel       3                0.15
260     rachel       9                0.11
261       ravi       8                0.03
262       ravi       9                0.11
263     robert       7                0.24
264     robert       8                6.06
265     robert       9                0.14
266    rolando       4                0.04
267    rolando       5                0.03
268       rolf       9                0.18
269       rory       7                0.03
270        roy       1                1.83
271        roy       2                1.50
272        roy       3                1.23
273        roy       5                0.18
274        roy       9                0.17
275       ryan       1                2.72
276       ryan       2                3.19
277       ryan       3                2.74
278       ryan       4                4.27
279       ryan       5                2.17
280       ryan       6                1.73
281       ryan       7                2.54
282       ryan       8                2.83
283       ryan       9                0.25
284      sasha       2                0.11
285      sasha       5                0.01
286      sasha       8                0.01
287    shirley       9                0.26
288    stanley       1                1.41
289    stanley       2                1.52
290    stanley       3                1.30
291    stanley       4                1.54
292    stanley       5                1.45
293    stanley       6                1.00
294    stanley       7                1.08
295    stanley       8                1.38
296    stanley       9                1.55
297  stephanie       5                0.08
298  stephanie       6                0.04
299      teddy       6                0.08
300       toby       1                1.20
301       toby       2                2.08
302       toby       3                1.69
303       toby       4                2.70
304       toby       5                0.90
305       toby       6                1.39
306       toby       7                1.38
307       toby       8                1.60
308       toby       9                1.92
309       todd       1                0.58
310       todd       2                0.35
311       todd       6                0.10
312       todd       7                0.60
313       todd       8                0.19
314       todd       9                0.25
315        tom       5                0.17
316        tom       6                0.10
317        tom       7                0.14
318       tony       3                0.33
319     trevor       9                0.47
320       troy       4                0.21
321       troy       9                0.02
322        val       8                0.84
323        val       9                0.26
324     vikram       4                0.21
325     vikram       5                0.13
326     walter       8                0.37
327       wolf       9                0.15
328       zeke       9                0.23

### Task #8. 

I will leave these undone since I didn't have time to accomplish them during the 4hr. chunk. However, here are a few questions which I would like to answer given more time:

1. Plot questions 1-7 to provide a more easily digestable report
1. Which season has the most dialogue (measured by number of words spoken)?
1. What is the average number of words spoken per scene across all seasons? Said another way, is there a given scene number which tends to have more dialogue than the other scenes?